Dockerfile: Bump builder to ART's Go 1.15 image
The outgoing docker.io image was subject to docker.io rate limiting
[1]:

  error: build error: failed to pull image: After retrying 2 times, Pull image still failed due to error: while pulling "docker://docker.io/openshift/origin-release:golang-1.13" as "docker.io/openshift/origin-release:golang-1.13"...

The new image matches openshift/cluster-version-operator@7cb2662924
(Updating cluster-version-operator builder & base images to be
consistent with ART, 2020-10-07,
openshift/cluster-version-operator#468).  Matching builders with the
CVO reduces our exposure by consolidating around a smaller set of Go
builder images.

I expect that after this lands, openshift/registry will pick it up via
a change like openshift/release@d0fa1c98b9 (Registry-replacer
autocommit, 2020-10-07, openshift/release#12532).

[1]: https://github.com/openshift/cincinnati-operator/pull/82#issuecomment-728254564