Merge branch '0.19-scaffolding-v1' into v1-crds
Generated by creating a fresh scaffold on top of 0.19-scaffolding
(described in the previous commit):

  $ git checkout -b 0.19-scaffolding-v1 0.19-scaffolding
  $ git rm -rf .
  $ operator-sdk-v0.19.3 init --domain openshift.io --repo github.com/openshift/cincinnati-operator
  $ operator-sdk-v0.19.3 create api --group updateservice --version v1 --kind UpdateService --resource --controller
  $ sed -i 's/cincinnati-operator/update-service-operator/' config/default/kustomization.yaml
  $ git add -A .gitignore *
  The following paths are ignored by one of your .gitignore files:
  bin
  cover.out
  hint: Use -f if you really want to add them.
  hint: Turn this message off by running
  hint: "git config advice.addIgnoredFile false"

We don't want to commit bin or cover.out, so the warning is fine.
This regenerates the file with the scaffolding for the new API name,
and we can merge it into our main branch to update the type there.
From [1], regenerating a new API is the prefered migration approach,
and running the '... create api ...' call directly in the main branch
gave:

  ...
  vet: functests/utils.go:79:53: SchemeGroupVersion not declared by package v1beta1
  make: *** [vet] Error 1
  Error: failed to create API with version "3-alpha": exit status 2
  ...
  FATA[0006] failed to create API with version "3-alpha": exit status 2

And then, back on master:

  $ git merge 0.19-scaffolding-v1
  $ emacs main.go api/v1/updateservice_types.go controllers/updateservice_controller.go # resolve conflicts
  $ emacs README.md Dockerfile controllers/*.go functests/*.go config/manifests/bases/cincinnati-operator.clusterserviceversion.yaml # remaining api/v1beta1 -> api/v1 migration and renames
  $ emacs config/samples/updateservice_v1_updateservice.yaml # copy some content from the outgoing Cincinnati sample
  $ git rm -f config/samples/cincinnati_v1beta1_cincinnati.yaml controllers/suite_test.go
  $ rm -rf bundle
  $ make generate manifests bundle
  $ git add -A README.md main.go api bundle config controllers functests

And then washing the merge out of the history:

  $ git branch temporary-merge
  $ git reset --hard HEAD^
  $ git rm -rf .
  $ git checkout temporary-merge -- .
  $ git commit
  $ git branch -D temporary-merge