*: Pivot from v1beta1 Cincinnati to v1 UpdateService
Generated with:

  $ git rm -rf .
  $ operator-sdk-v0.19.3 init --domain openshift.io --repo github.com/openshift/cincinnati-operator
  $ operator-sdk-v0.19.3 create api --group updateservice --version v1 --kind UpdateService --resource --controller
  $ sed -i 's/cincinnati-operator/update-service-operator/' config/default/kustomization.yaml
  $ git add -A .gitignore *
  The following paths are ignored by one of your .gitignore files:
  bin
  cover.out
  hint: Use -f if you really want to add them.
  hint: Turn this message off by running
  hint: "git config advice.addIgnoredFile false"

We don't want to commit bin or cover.out, so the warning is fine.
This regenerates the file with the scaffolding for the new API name,
and we can merge it into our main branch to update the type there.
From [1], regenerating a new API is the prefered migration approach,
and running the '... create api ...' call directly in the main branch
gave:

  ...
  vet: functests/utils.go:79:53: SchemeGroupVersion not declared by package v1beta1
  make: *** [vet] Error 1
  Error: failed to create API with version "3-alpha": exit status 2
  ...
  FATA[0006] failed to create API with version "3-alpha": exit status 2

[1]: https://github.com/operator-framework/operator-sdk/issues/560#issuecomment-522800054