Replace Handler with ProbeHandler to adjust to new K8s API version
As it is changed in kube version 0.23 and without the change tests
report below error.

controllers/new.go:585:4: unknown field 'Handler' in struct literal of type "k8s.io/api/core/v1".Probe
controllers/new.go:585:20: undefined: v1.Handler

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>